package com.excel.libraryManagementSystem.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Genre {
	FANTASY("FANTASY"),
	MYSTERY("MYSTERY"),
	SCIENCE_FICTION("SCIENCE_FICTION"),
	NOVEL("NOVEL"),
	NON_FICTION("NON_FICTION"),
	HISTORY("HISTORY"),
	BIOGRAPHY("BIOGRAPHY"),
	SPIRITUALITY("SPIRITUALITY"),
	POETRY("POETRY"),
	HUMOR("HUMOR"),
	DETECTIVE("DETECTIVE"),
	AUTOBIOGRAPHY("AUTOBIOGRAPHY"),
	PHILOSOPHY("PHILOSOPHY"),
	FAIRY_TALE("FAIRY_TALE"),
	COMICS("COMICS"),
	COOK_BOOKS("COOK_BOOKS"),
	TRAVEL("TRAVEL"),
	MUSIC("MUSIC"),
	ART_DESIGN("ART_DESIGN"),
	DRAWING("DRAWING"),
	VISUAL_ART("VISUAL_ART"),
	PHOTOGRAPHY("PHOTOGRAPHY"),
	BUSINESS("BUSINESS"),
	ECONOMICS("ECONOMICS"),
	POLITICS("POLITICS"),
	FINANCE("FINANCE"),
	MONEY("MONEY"),
	PSYCHOLOGY("PSYCHOLOGY"),
	TECHNOLOGY("TECHNOLOGY"),
	BIOLOGY("BIOLOGY");
	
	private final String genreType;
}
